sudo: required
services:
  - docker

before_install:
  - docker build -t besampson0/docker-tutorial -f Dockerfile.dev .

script:
  - docker run -e CI=true besampson0/docker-tutorial npm run test

language: generic

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker"
  bucket_name: "elasticbeanstalk-us-east-2-338526024944"
  bucket_path: "Docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
  