sudo: required
services:
  - docker

before_install:
  - docker build -t besampson0/docker-tutorial -f Dockerfile.dev .

script:
  - docker run -e CI=true besampson0/docker-tutorial npm run test

language: generic

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "bryce-docker"
  env: "Brycedocker-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-338526024944"
  bucket_path: "bryce-docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  